### ISSUE TITLE
Resources & Annotations: Map or String?

### ISSUE THREAD

**Issue by issacg** [hashicorp/vault-helm#292]
According to the docs [resources](https://www.vaultproject.io/docs/platform/k8s/helm/configuration#resources) and [annotations](https://www.vaultproject.io/docs/platform/k8s/helm/configuration#annotations) should be strings.

According to the defaults in values.yaml it seems that both should be maps.  Indeed trying to follow the docs gives me the following output:
```
coalesce.go:196: warning: cannot overwrite table with non table for resources (map[])
coalesce.go:196: warning: cannot overwrite table with non table for annotations (map[])
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].resources): invalid type for io.k8s.api.core.v1.ResourceRequirements: got "string", expected "map"
```

Are the docs wrong (outdated)? Or am I possibly doing something wrong?

I have an overrides file with snippets like these:
```yaml
injector:
  resources: |
    requests:
      memory: 64Mi
      cpu: 10m
    limits:
      memory: 256Mi
      cpu: 250m

server:
  ingress:
    annotations: |
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: vault
```

**Comment by pcman312** [comment]
Thanks for the issue! It looks like our documentation is incorrect. `resources` is a map type and `annotations` can be either a map type or a YAML-formatted multi-line string.

**Comment by oliviermichaelis** [comment]
I can confirm that removing the `|` works, but I still get the following warning:
```
coalesce.go:195: warning: destination for resources is a table. Ignoring non-table value <nil>
```
How do we get rid of the warning?


My overriding file looks like this:
```
server:
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m
```
and it templates out to this with `helm template`:
```
containers:
  - name: vault
    resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
```

**Comment by tvoran** [comment]
@issacg the docs for [resources](https://www.vaultproject.io/docs/platform/k8s/helm/configuration#resources) have been corrected. 

@oliviermichaelis that warning is because the default for `server.resources` is blank in values.yaml, which defaults to a string, so we just need to update the default to be `{}`. But for now it should be safe to ignore the warning.

**Comment by tvoran** [comment]
Resolved by #309 and https://github.com/hashicorp/vault/pull/8973

**Comment by maurya-m** [comment]
@tvoran has this being merged?  can you please help here?

i am still failing to install using the default values.yaml:

resources: {}
  # resources:
  #   requests:
  #     memory: 256Mi
  #     cpu: 250m
  #   limits:
  #     memory: 256Mi
  #     cpu: 250m

coalesce.go:195: warning: destination for resources is a table. Ignoring non-table value <nil>

NAME NAMESPACE REVISION UPDATED STATUS CHART APP VERSION
vault xxxx 1 2020-05-29 03:29:26.238520353 -0700 MST **failed** vault-0.5.0

**Comment by tvoran** [comment]
Hi @maurya-m, yes it's been merged into master. That warning shouldn't be preventing the chart from installing, so I think something else must be going on here. The output from `helm install` should have more information on why it failed, otherwise try the `--dry-run` and `--debug` flags with helm install to get more information.

**Comment by maurya-m** [comment]
@tvoran , thanks for replying here! I was able to deploy, the vault with now with global with false value:
`global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: **false**`
